#!/usr/bin/env python3
"""Export compact, offline browser data from the versioned manual/engine. MIT."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'docs/simulator/data.js'


def build():
    tables = json.loads((ROOT / 'manual/data/tables.json').read_text())
    weapons = json.loads((ROOT / 'manual/data/weapons.json').read_text())['weapons']
    keys = ('id', 'name_es', 'name_en', 'group', 'category', 'origin', 'damage_type',
            'dice_1h', 'dice_2h', 'fixed_damage', 'properties', 'mastery', 'usage_condition_es')
    data = {
        'version': tables['engine_version'],
        'engine_sha256': hashlib.sha256((ROOT / 'extension/scripts/arms_engine.lua').read_bytes()).hexdigest(),
        'weapons': [{k: w.get(k) for k in keys} for w in weapons],
        'profiles': tables['armor_profiles'],
        'families': {
            family: {
                armor: [[row['min'], row['quality']] for row in col['source_rows'] if row['hit']]
                for armor, col in info['columns'].items()
            } for family, info in tables['families'].items()
        },
    }
    return ('// Generated by tools/export_simulator.py; do not edit. Original experimental curves.\n'
            "(function(root){ 'use strict'; const data = " + json.dumps(data, ensure_ascii=False, separators=(',', ':')) +
            "; if(typeof module==='object' && module.exports) module.exports=data; else root.ARMS_DATA=data; })(globalThis);\n")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = build()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text() != expected:
            raise SystemExit('Browser data is stale. Run python3 tools/export_simulator.py')
        print('PASS browser catalog and all 56 armor columns match the versioned source.')
    else:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(expected)
        print(TARGET)
